# fly.toml app configuration file generated for lexspecifica on 2025-03-18T19:30:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lexspecifica'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8080"
  NODE_ENV = "production"
  # Do NOT add actual secret values here
  # Instead list variables that should come from Fly secrets
  # HF_MODEL = "" # Will be populated from Fly secrets