import { useState } from 'react';
import './App.css';
import heroImage from './assets/LexSpecifica.png';
import cityImage from './assets/city.jpeg';
import { generateFramework, generatePolicies, generateConflicts } from './api/client';
import InputForm from './components/InputForm';
import PolicyCard from './components/PolicyCard';
import ConflictsSection from './components/ConflictsSection';

function App() {
  const [worldConcept, setWorldConcept] = useState('');
  const [techLevel, setTechLevel] = useState(5);
  const [governmentType, setGovernmentType] = useState('');

  const [isGenerating, setIsGenerating] = useState(false);
  const [isGeneratingPolicies, setIsGeneratingPolicies] = useState(false);
  const [isGeneratingConflicts, setIsGeneratingConflicts] = useState(false);

  const [legalFramework, setLegalFramework] = useState(null);
  const [policies, setPolicies] = useState(null);
  const [conflicts, setConflicts] = useState(null);

  const [activeTab, setActiveTab] = useState('input');
  const [copyStatus, setCopyStatus] = useState('');

  const parameters = { techLevel, governmentType };

  const handleGenerateFramework = async () => {
    if (!worldConcept) return;
    setIsGenerating(true);
    try {
      const result = await generateFramework(worldConcept, parameters);
      setLegalFramework(result.legalFramework);
      setPolicies(null);
      setConflicts(null);
    } catch (error) {
      console.error("Error generating framework:", error);
      setLegalFramework(`Error: Failed to generate legal framework. ${error.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGeneratePolicies = async () => {
    if (!worldConcept) return;
    setIsGeneratingPolicies(true);
    try {
      const result = await generatePolicies(worldConcept, parameters);
      setPolicies(result.policies);
    } catch (error) {
      console.error("Error generating policies:", error);
    } finally {
      setIsGeneratingPolicies(false);
    }
  };

  const handleGenerateConflicts = async () => {
    if (!worldConcept) return;
    setIsGeneratingConflicts(true);
    try {
      const result = await generateConflicts(worldConcept, parameters);
      setConflicts(result.conflicts);
    } catch (error) {
      console.error("Error generating conflicts:", error);
    } finally {
      setIsGeneratingConflicts(false);
    }
  };

  const compileFullFramework = () => {
    if (!legalFramework) return null;

    let compiledContent = `# LEGAL FRAMEWORK FOR "${worldConcept.substring(0, 40)}${worldConcept.length > 40 ? '...' : ''}"\n\n`;
    compiledContent += `Technology Level: ${techLevel}/10\n`;
    compiledContent += `Government Type: ${governmentType || 'Unspecified'}\n\n`;

    compiledContent += `## LEGAL SYSTEM\n\n${legalFramework}\n\n`;

    if (policies && policies.length > 0) {
      compiledContent += `## KEY POLICIES\n\n`;
      policies.forEach((policy) => {
        compiledContent += `### ${policy.name}\n\n${policy.description}\n\n`;
      });
    }

    if (conflicts && conflicts.length > 0) {
      compiledContent += `## LEGAL CONFLICTS\n\n`;
      conflicts.forEach((conflict, index) => {
        // Handle both string and object formats
        const title = typeof conflict === 'object' ? conflict.title : `Conflict ${index + 1}`;
        const text = typeof conflict === 'object' ? conflict.text : conflict;
        compiledContent += `### ${title}\n\n${text}\n\n`;
      });
    }

    compiledContent += `---\nGenerated by LexSpecifica on ${new Date().toLocaleDateString()}\n`;
    return compiledContent;
  };

  const downloadFramework = () => {
    const content = compileFullFramework();
    if (!content) return;

    const filename = worldConcept
      .substring(0, 20)
      .replace(/[^a-z0-9]/gi, '_')
      .toLowerCase();

    try {
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}_legal_framework.md`;
      document.body.appendChild(link);
      link.click();

      setTimeout(() => {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }, 100);
    } catch (error) {
      console.error("Error during download process:", error);
    }
  };

  return (
    <div className="container" style={{ maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        marginBottom: '20px',
        background: 'linear-gradient(135deg, #2c3e50, #1a2a38)',
        padding: '0',
        borderRadius: '8px',
        color: 'white',
        overflow: 'hidden'
      }}>
        <div style={{
          width: '100%',
          height: '250px',
          backgroundImage: `url(${cityImage})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
        ></div>

        <div style={{ padding: '20px', textAlign: 'center', width: '100%' }}>
          <h1 style={{ fontSize: '32px', fontWeight: 'bold', marginBottom: '10px' }}>LexSpecifica</h1>
          <p style={{ fontSize: '18px', marginBottom: '20px' }}>Speculative Legal Framework Generator for Fiction Writers</p>

          <div style={{
            width: '100%',
            maxWidth: '700px',
            height: '400px',
            backgroundColor: '#1a2a38',
            borderRadius: '8px',
            marginBottom: '20px',
            backgroundImage: `url(${heroImage})`,
            backgroundSize: 'contain',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            margin: '0 auto 20px auto'
          }}></div>

          <div style={{
            backgroundColor: 'rgba(0,0,0,0.5)',
            padding: '15px 20px',
            borderRadius: '5px',
            maxWidth: '700px',
            width: '100%',
            textAlign: 'center',
            margin: '0 auto',
          }}>
            <span style={{ fontSize: '18px', fontWeight: 'bold' }}>
              Create realistic legal frameworks for your fictional worlds
            </span>
          </div>
        </div>
      </div>

      <div style={{ display: 'flex', borderBottom: '1px solid #ccc', marginBottom: '20px' }}>
        <button
          style={{
            padding: '10px 20px',
            backgroundColor: activeTab === 'input' ? '#3b82f6' : 'transparent',
            color: activeTab === 'input' ? 'white' : 'inherit',
            border: 'none',
            borderRadius: '4px 4px 0 0',
            cursor: 'pointer'
          }}
          onClick={() => setActiveTab('input')}
        >
          Create Framework
        </button>
        <button
          style={{
            padding: '10px 20px',
            backgroundColor: activeTab === 'instructions' ? '#3b82f6' : 'transparent',
            color: activeTab === 'instructions' ? 'white' : 'inherit',
            border: 'none',
            borderRadius: '4px 4px 0 0',
            cursor: 'pointer'
          }}
          onClick={() => setActiveTab('instructions')}
        >
          Instructions
        </button>
      </div>

      {activeTab === 'instructions' ? (
        <div style={{ padding: '20px', backgroundColor: '#f9f9f9', borderRadius: '8px', marginBottom: '20px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 'bold', marginBottom: '16px' }}>How to Use LexSpecifica</h2>
          {/* Condensed instructions for brevity in refactor proof-of-concept */}
          <p>1. Describe your world concept.</p>
          <p>2. Select tech level and government type.</p>
          <p>3. Generate framework, then explore policies and conflicts.</p>
        </div>
      ) : (
        <>
          <InputForm
            worldConcept={worldConcept}
            setWorldConcept={setWorldConcept}
            techLevel={techLevel}
            setTechLevel={setTechLevel}
            governmentType={governmentType}
            setGovernmentType={setGovernmentType}
            onSubmit={handleGenerateFramework}
            isGenerating={isGenerating}
          />

          {legalFramework && (
            <div style={{ marginTop: '32px', border: '1px solid #e2e8f0', borderRadius: '8px', overflow: 'hidden', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}>
              <div style={{ padding: '16px 20px', backgroundColor: '#2c3e50', color: 'white' }}>
                <h2 style={{ fontSize: '22px', fontWeight: 'bold' }}>Legal Framework for Your World</h2>
              </div>

              <div style={{ padding: '20px' }}>
                <div style={{ marginBottom: '24px', backgroundColor: '#f8f9fa', padding: '16px', borderRadius: '6px' }}>
                  <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '12px', color: '#2c3e50', borderBottom: '2px solid #3b82f6', paddingBottom: '8px' }}>Legal Framework</h3>
                  <div style={{ lineHeight: '1.6', whiteSpace: 'pre-wrap', textAlign: 'left' }}>
                    {legalFramework}
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', marginBottom: '24px' }}>
                  <button
                    style={{
                      flex: '1',
                      padding: '10px',
                      backgroundColor: policies ? '#f0f9ff' : '#3b82f6',
                      color: policies ? '#2c5282' : 'white',
                      border: policies ? '1px solid #3b82f6' : 'none',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontWeight: 'bold',
                      height: '60px'
                    }}
                    onClick={handleGeneratePolicies}
                    disabled={isGeneratingPolicies}
                  >
                    {isGeneratingPolicies ? 'Generating...' : policies ? '✓ Key Policies (Regenerate)' : 'Generate Key Policies'}
                  </button>

                  <button
                    style={{
                      flex: '1',
                      padding: '10px',
                      backgroundColor: conflicts ? '#fff5f5' : '#e53e3e',
                      color: conflicts ? '#c53030' : 'white',
                      border: conflicts ? '1px solid #e53e3e' : 'none',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontWeight: 'bold',
                      height: '60px'
                    }}
                    onClick={handleGenerateConflicts}
                    disabled={isGeneratingConflicts}
                  >
                    {isGeneratingConflicts ? 'Generating...' : conflicts ? '✓ Story Conflicts (Regenerate)' : 'Generate Story Conflicts'}
                  </button>
                </div>

                {policies && (
                  <div style={{ marginBottom: '24px' }}>
                    <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '12px', color: '#2c3e50', borderBottom: '2px solid #3b82f6', paddingBottom: '8px' }}>Key Policies</h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                      {policies.map((policy, index) => (
                        <PolicyCard key={index} policy={policy} />
                      ))}
                    </div>
                  </div>
                )}

                {conflicts && <ConflictsSection conflicts={conflicts} />}

                <div style={{ marginTop: '24px', display: 'flex', justifyContent: 'center', gap: '12px' }}>
                  <button
                    style={{
                      padding: '8px 16px',
                      backgroundColor: '#3b82f6',
                      color: 'white',
                      border: 'none',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontWeight: 'bold'
                    }}
                    onClick={() => {
                      setWorldConcept('');
                      setLegalFramework(null);
                      setPolicies(null);
                      setConflicts(null);
                    }}
                  >
                    Create New Framework
                  </button>
                  <button
                    style={{
                      padding: '8px 16px',
                      backgroundColor: 'transparent',
                      color: '#3b82f6',
                      border: '1px solid #3b82f6',
                      borderRadius: '4px',
                      cursor: 'pointer'
                    }}
                    onClick={downloadFramework}
                  >
                    Save Framework
                  </button>
                  {copyStatus && <span style={{ alignSelf: 'center', marginLeft: '10px', color: '#28a745', fontWeight: 'bold' }}>{copyStatus}</span>}
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default App;